name: LocalStack S3 Data Replication Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  localstack_test:
    runs-on: ubuntu-latest

    env:
      STAGE: test
      SOURCE_BUCKET: source-bucket
      DESTINATION_BUCKET: destination-bucket
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install AWS CLI
      run: |
        pip install awscli

    - name: Install pipenv
      run: |
        pip install pipenv

    - name: Install dependencies with pipenv
      run: |
        pipenv install --dev

    - name: Excecute Permission Script
      run: |
        chmod +x create_buckets.sh

    - name: Start LocalStack
      run: |
        docker compose up

    - name: Wait for LocalStack to be ready
      run: |
        until $(curl --head --fail http://localhost:4566/health); do
          printf '.'
          docker ps
          sleep 5
        done

    - name: Run tests with pytest
      run: |
        pipenv run pytest
