name: LocalStack S3 Data Replication Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  localstack_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install pipenv
      run: |
        pip install pipenv

    - name: Install dependencies with pipenv
      run: |
        pipenv install --dev

    - name: Excecute Permission Script
      run: |
        chmod +x create_buckets.sh

    - name: Start LocalStack
      run: |
        docker compose up -d

    - name: Wait for LocalStack to be ready
      run: |
        timeout=180
        elapsed=0
        container_id=$(docker ps --format "{{.ID}}")
        echo "Waiting for container $container_id to be healthy..."
        while [ "$(docker inspect --format='{{.State.Health.Status}}' $container_id)" != "healthy" ]; do 
          if [ $elapsed -ge $timeout ]; then
            echo "Timeout waiting for container $container_id to become healthy."
            exit 1
          fi
          sleep 5
          elapsed=$((elapsed + 5))
        done

    - name: Run tests with pytest
      run: |
        pipenv run pytest